"""Tests for the Verification Harness (agent/verify/harness.py).

SAFETY: every test that needs V2_COMPILE works against a fresh temp copy of
estate/dbt_project (see the `temp_project` fixture below) -- never the real
estate/dbt_project directory. This mirrors the harness's own contract and
avoids any risk of two concurrent dbt processes (this suite + a parallel
Phase 5 agent) writing to the same shared target/ directory.
"""
from __future__ import annotations

import shutil
import tempfile
from pathlib import Path

import pytest

from agent.verify import harness
from agent.verify.harness import verify_artifact
from agent.verify.models import V1_STATIC, V2_COMPILE

REPO_ROOT = Path(__file__).resolve().parents[1]
REAL_PROJECT = REPO_ROOT / "estate" / "dbt_project"


@pytest.fixture
def temp_project():
    """A throwaway copy of the real estate dbt project (target/ and logs/
    excluded -- they're regenerated by dbt and irrelevant to a fresh copy)."""
    tmp_root = Path(tempfile.mkdtemp())
    dest = tmp_root / "dbt_project"
    shutil.copytree(REAL_PROJECT, dest, ignore=shutil.ignore_patterns("target", "logs"))
    yield dest
    shutil.rmtree(tmp_root, ignore_errors=True)


def _overwrite_model(project_dir: Path, relative_path: str, sql: str) -> None:
    (project_dir / relative_path).write_text(sql)


# -- V1_STATIC ----------------------------------------------------------


def test_v1_static_passes_on_valid_sql(temp_project):
    report = verify_artifact("models/staging/stg_orders.sql", str(temp_project), levels=[V1_STATIC])
    assert report.passed is True
    assert len(report.outcomes) == 1
    outcome = report.outcomes[0]
    assert outcome.level == V1_STATIC
    assert outcome.passed is True
    assert outcome.raw_error is None


def test_v1_static_fails_with_substantive_raw_error_on_broken_sql(temp_project):
    # Dangling FROM clause with no table -- syntactically invalid SQL.
    _overwrite_model(temp_project, "models/staging/stg_orders.sql", "select order_id, cust_id from\n")

    report = verify_artifact("models/staging/stg_orders.sql", str(temp_project), levels=[V1_STATIC])

    assert report.passed is False
    outcome = report.outcomes[0]
    assert outcome.level == V1_STATIC
    assert outcome.passed is False
    # A useless "it failed" message would not let Loop 1 fix anything -- the
    # raw_error must actually be something an LLM could act on.
    assert outcome.raw_error
    assert len(outcome.raw_error) > 15
    assert "table" in outcome.raw_error.lower() or "expected" in outcome.raw_error.lower()


def test_v1_static_fails_on_mismatched_parens(temp_project):
    _overwrite_model(
        temp_project,
        "models/staging/stg_orders.sql",
        "select order_id from raw_orders where (order_id = 1\n",
    )

    report = verify_artifact("models/staging/stg_orders.sql", str(temp_project), levels=[V1_STATIC])

    assert report.passed is False
    assert report.outcomes[0].raw_error
    assert report.outcomes[0].raw_error.strip() != ""


# -- V2_COMPILE -----------------------------------------------------------


def test_v2_compile_passes_on_unmodified_real_model(temp_project):
    report = verify_artifact("models/staging/stg_orders.sql", str(temp_project), levels=[V2_COMPILE])

    assert report.passed is True
    outcome = report.outcomes[0]
    assert outcome.level == V2_COMPILE
    assert outcome.passed is True
    assert outcome.raw_error is None


def test_v2_compile_fails_with_substantive_raw_error_on_unresolvable_ref(temp_project):
    _overwrite_model(
        temp_project,
        "models/staging/stg_orders.sql",
        "select order_id, cust_id from {{ ref('does_not_exist_xyz') }}\n",
    )

    report = verify_artifact("models/staging/stg_orders.sql", str(temp_project), levels=[V2_COMPILE])

    assert report.passed is False
    outcome = report.outcomes[0]
    assert outcome.level == V2_COMPILE
    assert outcome.passed is False
    # This is exactly what Loop 1 will inject into its next generation
    # attempt -- it must name the actual missing dependency, not just say
    # "compile failed".
    assert outcome.raw_error
    assert "does_not_exist_xyz" in outcome.raw_error
    assert "not found" in outcome.raw_error.lower() or "depends on" in outcome.raw_error.lower()


def test_v2_compile_runs_after_v1_passes_for_a_ref_error_v1_cannot_catch(temp_project):
    # An unresolvable ref is syntactically valid SQL (V1's regex pre-pass
    # just turns it into a quoted identifier) -- only V2 can catch it. This
    # proves the two levels are checking genuinely different things.
    _overwrite_model(
        temp_project,
        "models/staging/stg_orders.sql",
        "select order_id, cust_id from {{ ref('does_not_exist_xyz') }}\n",
    )

    report = verify_artifact("models/staging/stg_orders.sql", str(temp_project))

    assert len(report.outcomes) == 2
    assert report.outcomes[0].level == V1_STATIC
    assert report.outcomes[0].passed is True
    assert report.outcomes[1].level == V2_COMPILE
    assert report.outcomes[1].passed is False
    assert report.first_failure is report.outcomes[1]


# -- ordering / short-circuiting -------------------------------------------


def test_v2_never_runs_when_v1_fails(temp_project, monkeypatch):
    calls = []

    def _spy_should_not_be_called(project_dir, model_name):
        calls.append((project_dir, model_name))
        raise AssertionError("V2_COMPILE must not run when V1_STATIC already failed")

    monkeypatch.setattr(harness, "_invoke_dbt_compile", _spy_should_not_be_called)
    _overwrite_model(temp_project, "models/staging/stg_orders.sql", "select order_id, cust_id from\n")

    report = verify_artifact("models/staging/stg_orders.sql", str(temp_project))

    assert calls == []
    assert len(report.outcomes) == 1
    assert report.outcomes[0].level == V1_STATIC
    assert report.passed is False


def test_full_pipeline_passes_on_unmodified_real_model_with_default_levels(temp_project):
    report = verify_artifact("models/staging/stg_orders.sql", str(temp_project))

    assert [o.level for o in report.outcomes] == [V1_STATIC, V2_COMPILE]
    assert report.passed is True
    assert report.artifact_path == "models/staging/stg_orders.sql"


# -- real-estate isolation --------------------------------------------------


def test_v2_compile_ignores_leaked_dbt_project_dir_env_var(temp_project, monkeypatch, tmp_path):
    # Regression test for the incident that motivated _dbt_subprocess_env:
    # this repo's own .env sets DBT_PROJECT_DIR, which dbt-core treats as a
    # real CLI-flag override that beats cwd/--project-dir-based resolution.
    # If a caller (e.g. the parallel Loop 1 self-correction loop, which
    # sources .env) has DBT_PROJECT_DIR set in its process when it calls
    # verify_artifact, the harness must still resolve the project it was
    # explicitly told to use -- not the leaked one. Point the decoy at an
    # empty bogus directory (never the real estate) so that even a broken
    # defense can only fail loudly against a decoy, never touch real data.
    bogus_decoy = tmp_path / "not_a_real_dbt_project"
    bogus_decoy.mkdir()
    monkeypatch.setenv("DBT_PROJECT_DIR", str(bogus_decoy))

    report = verify_artifact("models/staging/stg_orders.sql", str(temp_project))

    assert report.passed is True
    assert [o.level for o in report.outcomes] == [V1_STATIC, V2_COMPILE]


def test_verify_artifact_does_not_touch_the_real_estate_target_dir():
    real_manifest = REAL_PROJECT / "target" / "manifest.json"
    before = real_manifest.stat().st_mtime if real_manifest.exists() else None

    tmp_root = Path(tempfile.mkdtemp())
    dest = tmp_root / "dbt_project"
    shutil.copytree(REAL_PROJECT, dest, ignore=shutil.ignore_patterns("target", "logs"))
    try:
        verify_artifact("models/staging/stg_orders.sql", str(dest))
    finally:
        shutil.rmtree(tmp_root, ignore_errors=True)

    after = real_manifest.stat().st_mtime if real_manifest.exists() else None
    assert before == after
